name: apple
displayName: Apple Developer Documentation
baseUrl: https://developer.apple.com
extraction:
  primaryLanguage: swift
  selectors:
    content:
      - .documentation-content
      - .doc-content
      - main article
    title:
      - .topic-title h1
      - h1
    breadcrumb:
      - .navigator-breadcrumbs a
      - .hierarchy-list a
    version:
      - .availability
      - .platforms
    codeBlocks:
      - pre code
      - .code-listing code
pathMappings:
  swiftui: swiftui
  uikit: uikit
  foundation: foundation
  combine: combine
  appkit: appkit
stats:
  documentCount: 1
  lastUpdated: 2025-12-07T02:24:44.485Z
  lastCapturedAt: 2025-12-05T17:11:24.653Z
  topContributors: []
notes: |
  Apple Developer Documentation uses JavaScript rendering.
  Content must be captured via browser extension, not scraped.

  Version information is stored in frontmatter, not directory structure,
  because Apple URLs do not include version identifiers.
